//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoComplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRPORT
    {
        public long AIRPORTID { get; set; }
        public string AIRPORTName { get; set; }
        public string AIRPORTContinent { get; set; }
        public string AIRPORTISOCountry { get; set; }
        public string AIRPORTISORegion { get; set; }
        public string AIRPORTMunicipality { get; set; }
        public string AIRPORTIATACode { get; set; }
        public string AIRPORTCoordinates { get; set; }
    }
}
