//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoComplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class airport
    {
        public int ID { get; set; }
        public string AirportName { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string IATA_Code { get; set; }
        public string ICAO_Code { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> Altitude { get; set; }
        public Nullable<double> gmt { get; set; }
        public string DST { get; set; }
        public string Tz_database_time_zone { get; set; }
        public string Type { get; set; }
        public string Source { get; set; }
    }
}
